"""empty message

Revision ID: 0504861ea83c
Revises: f456bf688f65
Create Date: 2025-12-10 15:35:55.631746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0504861ea83c'
down_revision: Union[str, Sequence[str], None] = 'f456bf688f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_feedback_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('feedback_product_id_fkey'), 'feedback', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('feedback_product_id_fkey'), 'feedback', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('comments_feedback_id_fkey'), 'comments', 'feedback', ['feedback_id'], ['id'])
    # ### end Alembic commands ###
