"""empty message

Revision ID: 4cde5f6e0f31
Revises: 0504861ea83c
Create Date: 2025-12-11 14:38:19.286068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cde5f6e0f31'
down_revision: Union[str, Sequence[str], None] = '0504861ea83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
feedback_status_enum = sa.Enum(
    "NEW",
    "UNDER_REVIEW",
    "PLANNED",
    "IN_PROGRESS",
    "COMPLETED",
    "REJECTED",
    "DUPLICATE",
    name="feedbackstatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # create the enum type if it doesn't exist
    feedback_status_enum.create(bind, checkfirst=True)

    op.add_column(
        "feedback",
        sa.Column(
            "status",
            feedback_status_enum,
            nullable=False,
            server_default="NEW",
        ),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('feedback', sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'DUPLICATE', name='feedbackstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'status')
    # ### end Alembic commands ###
