"""empty message

Revision ID: b5b9b0891dd7
Revises: dc3d79b0cdd9
Create Date: 2025-12-08 14:06:11.170866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b9b0891dd7'
down_revision: Union[str, Sequence[str], None] = 'dc3d79b0cdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('organization_created_by_fkey'), 'organization', type_='foreignkey')
    op.create_foreign_key(None, 'organization', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.create_foreign_key(op.f('organization_created_by_fkey'), 'organization', 'users', ['created_by'], ['id'])
    op.alter_column('organization', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
