"""Delete on cascade for org and userid

Revision ID: dc3d79b0cdd9
Revises: bea78b1123a6
Create Date: 2025-11-27 13:06:34.269856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3d79b0cdd9'
down_revision: Union[str, Sequence[str], None] = 'bea78b1123a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oragnizationmembership_org_id_fkey'), 'oragnizationmembership', type_='foreignkey')
    op.drop_constraint(op.f('oragnizationmembership_user_id_fkey'), 'oragnizationmembership', type_='foreignkey')
    op.create_foreign_key(None, 'oragnizationmembership', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'oragnizationmembership', 'organization', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'organization', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_constraint(None, 'oragnizationmembership', type_='foreignkey')
    op.drop_constraint(None, 'oragnizationmembership', type_='foreignkey')
    op.create_foreign_key(op.f('oragnizationmembership_user_id_fkey'), 'oragnizationmembership', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('oragnizationmembership_org_id_fkey'), 'oragnizationmembership', 'organization', ['org_id'], ['id'])
    # ### end Alembic commands ###
